### ISSUE TITLE
tgroup command not working

### ISSUE THREAD

**Issue by javrav2** [packetchaos/navi#11]
Just ran 'navi tgroup --name "AWS Assets Public IPs" -aws -pub'. Getting error saying No such command 'tgroup'.

**Comment by packetchaos** [comment]
I just released a new version of navi last night. Please reinstall navi and try again.

pip3 uninstall navi-pro
pip3 install navi-pro

**Comment by packetchaos** [comment]
I resolved the bug and pushed out a new version. Please reinstall navi and let me know if there are any other issues.

Thanks,
