### ISSUE TITLE
View and Modify Tenable.io User Authorizations?

### ISSUE THREAD

**Issue by NateUT99** [packetchaos/navi#19]
Is it possible to view and modify Tenable.io user authorizations (api_permitted, password_permitted, saml_permitted) using Navi?

Reference: https://developer.tenable.com/reference#users-list-auths

**Comment by packetchaos** [comment]
Yes, Today it is possible to view;  ironically I pushed that capability out
yesterday.  `navi display auth <user_uuid>`

This weekend I am pushing out the ability to change those settings via navi.

**Comment by NateUT99** [comment]
Perfect timing! :)

Thanks,
Nate

**Comment by packetchaos** [comment]
I just pushed the capability out.  If you need it today, you can clone the
repo and install from the setup.py file.

`navi user enable <user_uuid> -saml`.  --- This command will enable saml
and disable API and Password login.

you could alternatively use the disable command

`navi user disable <user_uuid> -api -pwd` --- this command will disable API
and Password and enable saml

git clone https://github.com/packetchaos/navi.git

cd to navi

python3 setup.py install

I will be finishing documentation this weekend and pushing it to pip on
Sunday Night.
