### ISSUE TITLE
Navi http not found in latest docker version

### ISSUE THREAD

**Issue by spiffycell** [packetchaos/navi#28]
It seems that `navi http` is not working in its latest version on the docker container:

```
root@49cf67e0a40f:/usr/src/app# navi http Usage: navi [OPTIONS] COMMAND [ARGS]... Try 'navi --help' for help. Error: No such command 'http'.
```

**Comment by packetchaos** [comment]
This command was removed in favor of Navi being supported by Tenable.  

The `navi http` command was running `python3 -m http.server` in the background.

I will add this to the documentation.
