### ISSUE TITLE
Update Wiki on how to locally mount Navi.db

### ISSUE THREAD

**Issue by spiffycell** [packetchaos/navi#29]
When running Navi as a docker image, to visualize the local data cached from SQLite in a tool like dbeaver, I need to add a `-v $HOME/.navi/navi.db:/usr/src/app/navi.db` in the `run` command.

Can this be clarified in the Wiki for folks who want to use the docker image, but also want to use a local DB tool?

**Comment by packetchaos** [comment]
So I understand the ask.  Are you looking to mount the Navi.db on the local host rather than inside of the container?

**Comment by spiffycell** [comment]
Correct, use the container's environment, but mount the navi.db locally

**Comment by packetchaos** [comment]
Aright.  I updated the documentation with the following line:

docker run -it -p 8000:8000 --mount type=bind,source="$(pwd)",target=/usr/src/app silentninja/navi /bin/bash

This will mount the container to the local host. 

Thank you for calling this out!
