### ISSUE TITLE
Does it work onpermise installation of tenable.sc ?

### ISSUE THREAD

**Issue by xoroz** [packetchaos/navi#36]
Sorry for the dumb question but I looked everywhere and I am unable to understand.
Can I configure navi to talk to my local tenable.sc (Security Center) Setup ? 
I do have my API keys but I find no option on how to point to my local server

thanks

**Comment by packetchaos** [comment]
Navi only works with Tenable Vulnerability management(TVM formally
tenable.io). Although, you can move data between TVM and Tenable Security
Center(TSC).

However, Ivan works with TSC and is a bit behind in capabilities but I'm
working towards expansion.

https://github.com/packetchaos/ivan

**Comment by packetchaos** [comment]
Let me know if you have any questions on ivan or navi.  Closing the ticket.
