### ISSUE TITLE
Feature: A running timer or another way to display `PROCESSING`

### ISSUE THREAD

**Issue by jbpratt** [packetchaos/navi#6]
Currently running an update that gets everything (made it way longer than previously, at least 25m+ so far). It would be nice to see a timer of how long the processing has been going on. It doesn't seem like a progress bar would make sense here unless it could actually be calculated (doubt it).

**Comment by packetchaos** [comment]
That is a good idea.  Can you submit a FR on github so I can track it.

**Comment by packetchaos** [comment]
I looked into this further today.  The "processing" is coming from the Tenable.io API.  There is no endpoint to check for how long that job will stay in processing.  The master branch is set to check in on the status of the Export request every 5 seconds.  I made a change to the dblock branch to increase that setting to 15 seconds and added the number of chunks available for download and what chunk the program is currently parsing.

**Comment by packetchaos** [comment]
I added a timer for each portion of the export.  The goal is to give you greater insight into how long it is taking and how long it might take.  I'm going to work out an algorithm to guess progress time in a later version.

**Comment by jbpratt** [comment]
> I added a timer for each portion of the export. The goal is to give you greater insight into how long it is taking and how long it might take. I'm going to work out an algorithm to guess progress time in a later version.

Great, I have no clue if the progress time can be properly estimated. It could depend on numerous things impacting the host of the Tenable.io instance (not even sure of what kind of hardware it is running on). I'm not sure how the back end API handles querying or caching the data as well as if there is another process on the server like the results from a scanner, etc. Just thoughts, keep up the awesome work. I had a Tenable Support staff recommend this tool, btw. :+1:
