### ISSUE TITLE
Install seems simple but having issues connecting to tenable API

### ISSUE THREAD

**Issue by cbeyertn** [packetchaos/navi#9]
root@ubuntu:/home/rocket/Desktop# navi display -scanners
Hey Listen!
Something went wrong...Don't be trying to hack me now <Response [401]>

Scanner Name                        Scanner ID           Scanner UUID
----------------------------------------------------------------------------------------------------
Check your API keys or your internet connection
I received the following Error: 
 
'NoneType' object is not subscriptable
root@ubuntu:/home/rocket/Desktop# 

I know the keys are correct because they are displayed while running command --- navi find --query "select * from keys;"

**Comment by cbeyertn** [comment]
Please assist in getting this working

**Comment by packetchaos** [comment]
It looks like you may not be an admin.  For most of the calls in Navi you need to be a Tenable.io admin.

Try "navi api /scanners".  

Also try "navi display -status"

if both of those fail, your keys are inputted incorrectly or you are not an admin in Tenable.io

**Comment by cbeyertn** [comment]
root@G111LCND8290PNQ:/home/rocket# navi api /scanners
Hey Listen!
Something went wrong...Don't be trying to hack me now <Response [401]>
None
root@G111LCND8290PNQ:/home/rocket#

I am admin and the keys are correct as I'm able to use Postman to connect via API

**Comment by cbeyertn** [comment]
root@G111LCND8290PNQ:/home/rocket# navi display -status
Hey Listen!
Something went wrong...Don't be trying to hack me now <Response [401]>

Tenable IO Information
-----------------------
Check your API keys or your internet connection
I received the following Error:

'NoneType' object is not subscriptable
root@G111LCND8290PNQ:/home/rocket#

**Comment by packetchaos** [comment]
There must be a space in your keys or something like that. The API command
is sending a simple GET request similar to postman.

**Comment by cbeyertn** [comment]
Can you provide the a sample of the proper format?

**Comment by packetchaos** [comment]
Here is what the Keys look like in the UI
<img width="520" alt="Screen Shot 2020-07-15 at 4 38 42 PM" src="https://user-images.githubusercontent.com/32307917/87610393-182c6200-c6ba-11ea-89fc-f69feca1a08e.png">

And how they should show up after running this command
<img width="714" alt="Screen Shot 2020-07-15 at 4 40 44 PM" src="https://user-images.githubusercontent.com/32307917/87610401-1e224300-c6ba-11ea-9eac-9c7fcd155427.png">

If it is not working, I would suggest regenerating your keys and trying again.
